Events page
uwblueprint/dancefest-android pull request #12
Opened 2019-01-15 01:19 UTC by danielpeng2

Created Events activity with RecyclerView to display data.
Retrieves data from Firebase on activity start and whenever Firestore is updated.

2019-01-15 02:14 UTC, YangStephen requested changes
First round of review questions.

2019-01-15 02:14 UTC, YangStephen commented on app/build.gradle
> +    implementation 'com.android.support:recyclerview-v7:26.1.0'
move this up and order it alphabetically

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                Log.w(TAG, "Listen failed", e)
should this be logged as an error or warning?

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                val data = doc.data
https://kotlinlang.org/docs/reference/multi-declarations.html

We can destructure this in 1 line :)

val (id, data) = doc;

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +class EventsAdapter(private val events: ArrayList<Event>) :
Is events not already private?

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +        RecyclerView.Adapter<EventsAdapter.ViewHolder>() {
This formatting is off, https://kotlinlang.org/docs/reference/coding-conventions.html#class-header-formatting

This should be inline with the classes and functions below, not offset by another space.

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +                .inflate(R.layout.item_event, parent, false)
Why is this so far indented?

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +        }
This should end around the same spot as where the .addOnFailureListener ended no? Also is it possible to move this onto one line if it does not pass 100 characters.

2019-01-15 02:14 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +    override fun getItemCount() = events.size
Can we alphabetize these function declarations.

2019-01-15 02:16 UTC, mark-azer reviewed
Ok looks good on my end

2019-01-15 02:16 UTC, mark-azer commented on app/src/main/java/com/uwblueprint/dancefest/Event.kt
> +}
These curly braces are redundant

2019-01-15 03:30 UTC, YangStephen requested changes
Ok, quick second round look-over.

2019-01-15 03:30 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +    private lateinit var firestoreUtils: FirestoreUtils
Can we alphabetize the firestoreUtils above the others.

2019-01-15 03:30 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +            events = arrayListOf()
So it looks like `arrayListOf` returns you what is the equivalent of an empty ArrayList.

For general code practices, I think we should have strict types on any objects we create that are of type `<T>`, https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/array-list-of.html

In this case, `arrayListOf<Event>()`;

2019-01-15 03:30 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +            for (doc in value!!) {
To verify something: Should we make this Nullsafe. it appears is value is null, this throws a `KotlinNullPointerException`

2019-01-15 03:30 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +        var nameView: TextView = view.name_text
So I'm not sure if Kotlin supports this like Javascript does, but JS supports:
```
const {
  name_text: nameView, // rename view.name_text -> a variable called nameView
  date_text: dateView // rename view.date_view -> a variable called dateView
} = view;
```

Something to investigate

2019-01-15 03:30 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +        holder.nameView.text = events[position].name
`events[position]` is called 3x here, each of which is an array access. In this case, I'd consider us only accessing the events array once, and fetching that object into it's own variable in this method.

Then accessing that variable for all calls to events[position] as the events[position] stays constant for any given call to this function.

2019-01-16 21:05 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                Log.w(TAG, "Listen failed", e)
Probably an error, I'll fix this.

2019-01-16 21:10 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                val data = doc.data
The QuerySnapshot type doesn't have a 'component1()' or 'component2()' function implemented, so I get an error if I try to use it.
![image](https://user-images.githubusercontent.com/30786057/51278625-1bea0600-19a9-11e9-975d-76ced9f50add.png)

2019-01-16 21:17 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +class EventsAdapter(private val events: ArrayList<Event>) :
I think in Kotlin the default visibility modifier is public.

2019-01-16 21:40 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +            events = arrayListOf()
Since we defined events as an ArrayList<Event>, I think we don't have to put the explicit type there. Android Studio tells me that we don't need it.
![image](https://user-images.githubusercontent.com/30786057/51280333-5fdf0a00-19ad-11e9-9b7c-8f7966f88eb6.png)

2019-01-16 22:17 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +        var nameView: TextView = view.name_text
I checked the documentation for deconstructive declarations in Kotlin and couldn't find anything

2019-01-16 22:20 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +                .inflate(R.layout.item_event, parent, false)
This was just the default formatting that Android Studio gave me, I decreased the indent by a tab for now.

2019-01-17 13:31 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                val data = doc.data
Let me take a look at this, it looks like Kotlin should auto-generate component functions for this use.

`Component functions generated for data classes enable their use in destructuring declarations:` - https://kotlinlang.org/docs/reference/data-classes.html

2019-01-17 17:10 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                val data = doc.data
Ok, following up on this, don't worry about it. I realized that QueryDocumentSnapshot is a public class provided to us by Google, so it's not a data class and cannot be destructured as such. We can maintain it as previously declared

2019-01-17 17:15 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +            events = arrayListOf()
Ah, I see, you added the type into the events declaration. This is fine :)

2019-01-17 22:18 UTC, YangStephen requested changes
Really awesome job @danielpeng2, This will likely be my last set of comments before approval.

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +        list_events.apply {
Let's standardize this styling, this could likely be one line like line 58 in this file

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                    events.add(Event(title as String, date.toString(), id))
So this logic will actually exclude events in it's entirety if title or date is null. We shouldn't exclude events, we should try to render them as much as possible, even if a value is null, we can put in a default "MISSING" or "NA" tag.

Additionally, once we figure out what we want to do, if there is a title or date that fails, let's also log it :)

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +        // initialize recyclerview
NIT: Can we capitalize these comments and make them grammatically correct?

`// Initialize RecyclerView`

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +class EventActivity : AppCompatActivity() {
Let's add class comments on these activities to describe what they manage and any expected behaviour for bundles that might occur.

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +        // set the title of the action bar
Capitalize first letter

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +    class ViewHolder(val view: View) : RecyclerView.ViewHolder(view) {
Do we want this view to be private to the class? As mentioned, Kotlin has public default visibility.

2019-01-17 22:18 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +            // TODO: go to event detail page
Capitalize G and keep this grammatically correct please :)

`// TODO: Go to the event detail page.`

2019-01-18 04:02 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +    class ViewHolder(val view: View) : RecyclerView.ViewHolder(view) {
I wouldn't be able to call view.setOnClickListener later on in EventsAdapter if we set view to be private.

2019-01-18 14:48 UTC, YangStephen approved these changes
Minus a few very nit comments, LGTM @danielpeng2 🚢

2019-01-18 14:48 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                if (title == null) Log.e(TAG, "Null title")
Can log.e receive an object? These logs aren't that helpful without some sort of identifier or representation of the data object that's null.

2019-01-18 14:48 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +// Manages and displays the Events Page
Period here :)

2019-01-18 14:48 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +        const val TAG = "EVENT_ACTIVITY"
In any object, let's alphabetize the declarations

2019-01-18 14:48 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/Event.kt
> +data class Event(val name: String, val date: String, val eventId: String)
Does the constructor for the data class require the parameters be provided in order? If not, let's alphabetize this.

2019-01-18 15:57 UTC, merged