Implement a centralized ID generator class "IDFetcher" with Firebase
uwblueprint/dancefest-android pull request #14
Opened 2019-01-26 22:33 UTC by Dendrimer

Introduce a class that generates unique IDs using a counter. This class checks if the calling device's serial # is present, returning the stored ID if it is present, otherwise generating a new one.

2019-01-27 20:59 UTC, YangStephen requested changes
Nice Franz! Not many comments, just a few questions and styling changes

2019-01-27 20:59 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +        const val TAG = "IDFetcher"
for object's, let's alphabetize by the name

2019-01-27 20:59 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +            if (document != null && document.data != null) {
could't this check be extracted to a single statement like val documentData = document?.data.

Then we check if documentData is null and we could also use this to do a documentData?.get on line 49?

2019-01-27 20:59 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +    fun registerCallback(callback: (Long?) -> Unit) {
Just to verify, is the reason why we invoke the callback rather than return the answer is for the asynchronous nature of the firebase calls?

2019-01-27 20:59 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +                        newVal
So I assume that this is a return value that is returned? 

This may be nitty but we could probably  change the return so that we don't return from within an if statement but instead return a single value.

Ex.
```
val retVal = 0;
if (...) {
   retVal = newVal;
} else {
...
}
retVal; <- returns 0 in the else case, newVal in the if case.
```

2019-01-27 20:59 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +                    Log.i(TAG, "Failed to commit new ID for device ${Build.SERIAL}")
Log.e please :)

2019-01-27 21:10 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +    fun registerCallback(callback: (Long?) -> Unit) {
Yeah, that's exactly the reason.

2019-01-29 00:26 UTC, YangStephen approved these changes
Approved conditionally on the Long change + the change on line 19

2019-01-29 00:44 UTC, merged