Adjudication
uwblueprint/dancefest-android pull request #15
Opened 2019-01-29 04:27 UTC by sophieq

2019-01-29 13:46 UTC, YangStephen requested changes
V1 Lookover

2019-01-29 13:46 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".CritiqueFormActivity"
For this PR, let's not change the default activity. Theoretically, users should be transitioning to the CritiqueFormActivity from EventActivity

2019-01-29 13:46 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            val data = HashMap<String, Any?>()
Apparently there is a Kotlin version of this where we can initialize all of lines 51 - 56 in 1.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/hash-map-of.html

2019-01-29 13:46 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                cumulativeScore = (artisticScore + technicalScore) / 2
Should we consider maybe making the default score -1? Then if the score is -1, we show "N/A", else the score?

2019-01-29 13:46 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        if (navPath.count() >= 60) {
what is navPath?

2019-01-29 15:04 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        val btnSave = findViewById<Button>(R.id.saveButton)
In Kotlin there's automatic viewbinding: https://kotlinlang.org/docs/tutorials/android-plugin.html.
So instead of getting the button from findViewById you can directly call saveButton.setOnClickListener below.

2019-01-29 17:25 UTC, sophieq commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        if (navPath.count() >= 60) {
it is the title at the top of the card, under the navigation bar
![screen shot 2019-01-29 at 12 25 10 pm](https://user-images.githubusercontent.com/32018650/51927173-f73a5900-23c0-11e9-9a67-5e0ab5fb2ee0.png)

2019-01-29 17:28 UTC, sophieq commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".CritiqueFormActivity"
Okay, should I make it so the CritiqueFormActivity appears when pressing an event in the EventActivity then or leave them disconnected? Since the Performance Activity is not present in this branch, there's not way to segue into CritiqueFormActivity

2019-01-29 17:47 UTC, danielpeng2 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".CritiqueFormActivity"
In the master branch I think we want to leave it disconnected for now, since we should be transitioning to CritiqueFormActivity from PerformanceActivity.

2019-01-29 19:10 UTC, sophieq commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".CritiqueFormActivity"
Oh ok true that makes sense

2019-01-29 19:25 UTC, Dendrimer approved these changes
Great job overall, just a few nits and other than the comments that Daniel/Stephen made it should be good 💯

2019-01-29 19:25 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +import android.widget.Toast
Ideally, imports are imported alphabetically.

2019-01-29 19:25 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            val data = HashMap<String, Any?>()
Yeah, the code would look something like:
`hashMapOf("artisticMark" to artisticScore, "technicalMark" to technicalScore, ...etc)`

2019-01-29 19:25 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        // Current placeholders for information passed from the previous activity.
You should put a TODO here to remove this stuff so we don't forget to delete this stuff when the data is properly passed from the performances page

2019-01-29 19:26 UTC, Dendrimer commented
Another general comment about PRs and making the process better is to write a few sentences about the PR so that the reviewers have some context about what you were trying to achieve.

2019-02-25 16:39 UTC, YangStephen commented
@sophieq Also: is this one required?

2019-02-25 17:07 UTC, sophieq commented
@YangStephen I think the changes in this pr get applied in the Adjudication forms pr because the branch adjudication_new was branched off this one

2019-02-26 01:35 UTC, closed without merging