Adjudication forms
uwblueprint/dancefest-android pull request #19
Opened 2019-02-12 00:38 UTC by sophieq

Adding creation of adjudication forms, editing forms and sending data to Firebase.

2019-02-12 02:49 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/Performance.kt
> +package com.uwblueprint.dancefest
I think this is a duplicate performance class of the one in the models package?

2019-02-12 03:04 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            adjudication = intent.getSerializableExtra("adjudication") as Adjudication
I think I only pass the Adjudication when there's an existing adjudication for the current tabletID, so there's a scenario when this will return null for adjudication. We can also deal with this when we link up the screens though.

2019-02-24 18:24 UTC, YangStephen requested changes
Let's try to get this in tomorrow :). Only main comment is to refine the testing code you have to instead come from the Bundle.

2019-02-24 18:24 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        eventId = "G25liC0iKFYcZFG3l2d6"
Can we shift these variables to be reliant on the Bundle coming in?

2019-02-24 18:24 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        tabletId = "3"
We should also take a look at Franz's merged change for getting the tabletID to be used here.

2019-02-24 18:24 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +
extra line

2019-02-24 18:24 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            val data: HashMap<String, Any?> = hashMapOf("artisticMark" to artisticScore,
I think it may be a bit more readable to add each hashMap parameter on a new line

```
hashMapOf(
   ...
   ...
   ...
)
```

2019-02-24 18:24 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +
extra line

2019-02-24 18:24 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                        numJudges = "",
Just to verify, we don't want the default check here?

2019-03-02 20:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        if (adjudication != null) {
If the Intent is null, can the adjudication ever be non-null? I think this may want to be bundled into the if (intent!=null) call.

2019-03-02 21:20 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        // Current placeholders for information passed from the previous activity.
Delete these comments since we're passing the values from the previous activity now.

2019-03-03 16:50 UTC, YangStephen requested changes
Nice job Dan & Sophie, let's get these taken a look at and we should be close :)

2019-03-03 16:50 UTC, YangStephen commented on app/build.gradle
> +    implementation 'com.android.support:cardview-v7:28.0.0'
Can we move these with the other implementations?

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        // TODO: Remove Placeholders.sxz
What is placeholders.sxz?

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            technicalScoreInput.setText("")
can these be grouped into 1 statement? like artisticScoreInput.set(if adjudication != null adjudication?.artisticMark.toString() else ""),

Also we may want to define a const emptyString to empty Data here.

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            technicalScoreInput.setText(adjudication?.technicalMark.toString())
Should these also use ?.toString() ? If adjudication.artisticMark returns null, I'd think that toString will throw an exception

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            var artisticScore = artisticScoreInput.text.toString().toIntOrNull()
is there a way to go to toIntOrNull without the toString?

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            if (artisticScore == null) {
For all of these if `xScore == null, xScore = 1` statements, I think we could just use the elvis operator instead

`var technicalScore = technicalScoreInput.text.toString().toIntOrNull() ?: -1`

ref: https://medium.com/tompee/idiomatic-kotlin-elvis-operator-d6f5639a5130

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                    "artisticMark" to artisticScore,
Let's keep a 4 space indent here.

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            val data: HashMap<String, Any?> = hashMapOf(
I'm curious if this `Any` type actually includes null, as then we wouldn't need `Any?`.

Also, which one of these values are nullable? it appears all of the scores reduce to integer values. is it JudgeNotes or tabletId?

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                    "CRITIQUE SAVED",
4 space indent please

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +
extra line

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +    private lateinit var pagerAdapter: FragmentStatePagerAdapter
Let's alphabatize all of these variable declarations. It's also a bit chunky here so I'd be ok if we did segment them apart fo readability.

For example, all the Performance Activity vars like `database` `event` , etc. together.

The adjudication declaration and the adjKeys together.

completedPerformances, incompletePerformances, and perfKeys together.

Though any logical grouping should be fine. Just to improve readability.

```
One Group
<New Line Space>
Second Group
<New Line Space>
...
```

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +            tabletID = id
Have you tested this binding? I just want to ensure that our callback is binding to the class here rather than to the IDFetcher class.

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                                            adjDocData?.get(adjKeys.ARG_CUMULATIVE_MARK)
There's an extra indent that got added here.

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                    val countDownLatch = CountDownLatch(it.size())
What is this `it` variable and where is it coming from?

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +            firstRun = false
This firstRun variable is only used 3 times in this PR, during the declaration, the check and then setting it to false.

Why are we skipping this database call when the firstRun is true? In that case, wouldn't there be no data the first time we show this? When is the data being populated for the first time?

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                    completePerformances.clear()
Before we clear everything, should we verify that all the data we are getting is valid? Also, this onSuccessListener only encapsulates the Performances call.

I'd say that the adjudications.clear() on line 179 should be covered by the call that starts on line 207.

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                .collection(COLLECTION_EVENTS)
could we also use a string path to fetch the collection here rather than the 3 nested calls? Like lines 208 - 210.

2019-03-03 16:50 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformancePagerAdapter.kt
> +    override fun getItemPosition(`object`: Any): Int {
What's this notation? 
```
`object`: Any
```

2019-03-03 17:31 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                    val countDownLatch = CountDownLatch(it.size())
It's an implicit parameter in the lambda function. If a function only has 1 parameter, you can omit the declaration use "it".

2019-03-03 18:13 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +            tabletID = id
I'm not really sure what you mean by this?

2019-03-03 18:20 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +            firstRun = false
There's a database call in the onCreate and onResume lifecycle methods. The call in the onCreate gets the data and initializes/sets the data in the adapter, while the call in the onResume gets the data and tells the adapter that the data has been updated. On opening performances page, both the onCreate and onResume will run, but I only want the call in onCreate to run in this scenario.

2019-03-03 18:27 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                    completePerformances.clear()
How should we check if the data is valid?

We can't call adjudications.clear() in the call on line 207 since that call runs once for each performance. Clearing it there would mean we clear out the data with each performance and our final list would only have one item in it.

2019-03-03 18:29 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformancePagerAdapter.kt
> +    override fun getItemPosition(`object`: Any): Int {
It's just a variable name of an object. The single quotes are there because "object" is a keyword in Kotlin so we can't use it as a standalone variable name. It was the name that Android Studio auto-generated for me, I can change it to something more descriptive if that works better.

2019-03-03 19:50 UTC, Dendrimer reviewed
Don't have any other comments to add onto Stephen's review, fix that and LGTM. Great job you two!

2019-03-05 01:35 UTC, YangStephen approved these changes

2019-03-05 01:59 UTC, merged