Performances page
uwblueprint/dancefest-android pull request #20
Opened 2019-02-15 05:33 UTC by danielpeng2

Finished getting the Performances and Adjudications (corresponding to the tabletID) from Firebase, displaying in the tabbed layout. Ready to link with Adjudications page that Sophie made.
![screenshot_1550208642](https://user-images.githubusercontent.com/30786057/52836531-f7bd3a00-30b8-11e9-9a87-60f1fc84d5ca.png)
![screenshot_1550208646](https://user-images.githubusercontent.com/30786057/52836532-f7bd3a00-30b8-11e9-94fe-79a59369d57f.png)

2019-02-20 23:25 UTC, YangStephen requested changes
First run through.

2019-02-20 23:25 UTC, YangStephen commented on app/build.gradle
> +    implementation 'com.android.support:design:26.1.0'
let's group this with the other implementation imports

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventItemListener.kt
> +}
File is missing a new line terminator.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventItemListener.kt
> +interface EventItemListener {
Nice use of OOP here :)

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +}
New line terminator.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceItemListener.kt
> +}
New Line Terminator.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/models/PerformancesAdapter.kt
> +}
New Line

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/models/PerformancesAdapter.kt
> +        holder.nameView.text = performance.danceTitle
If Performance is a data class, let's destructure danceTitle and performanceId here

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/res/layout/item_performance.xml
> +</android.support.constraint.ConstraintLayout>
new line

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/res/layout/fragment_performance.xml
> +</android.support.constraint.ConstraintLayout>
NL

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/res/layout/activity_performance.xml
> +
This may be a double new line haha, let's cut this down to just one new line terminator on the file.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/res/layout/activity_event.xml
> +
Let's remove this new line and minimalize the diff here.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +    private lateinit var adjudications: HashMap<*, *>
Why does the adjudications hash map take all types?

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +    fun registerCallback(db: FirebaseFirestore, callback: (Long) -> Unit) {
Can we add a few comments about what this db variable is? Something about where we should be fetching a db instance from and how it propagates to here? Also, why does the above getInstance not work in this case?

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                        //numJudges = if (numJudges == null) DEFAULT else numJudges as String
Which one of these two numJudges are we using?

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +    companion object {
I really like the use of these consts to declare the type. is there a way to maybe move the `ARG_<ARGNAME>` variables into the corresponding Performance data class and just import them? It'd be nice if the object itself also held onto what we expect as ARGS.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +
extra line

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                .addSnapshotListener { performanceValue, performanceE ->
Can we specify exactly what `performanceE` is? or just call it error or something here?

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                                    val adjDoc = it.documents[0]
We may just want to fetch adjDoc.data here and just call .get on all further calls rather than both .data?.get

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                            .collection(COLLECTION_PERFORMANCES)
we may just be able to truncate this by providing the path to a given value instead.

Something like `"/events/${event.eventId}/performances/${performanceDoc.id}..."` and call the .whereEqualTo function from there.

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                    putParcelableArrayList(TAG_PERFORMANCES, incompletePerformances)
if these 2 function calls are essentially the same, can we do something like `putParcelableArrayList(TAG_PERFORMANCES, if(position == 0) incompletePerformances else completePerformances`

2019-02-20 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +}
New Line

2019-02-21 04:18 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/models/PerformancesAdapter.kt
> +        holder.nameView.text = performance.danceTitle
Since danceTitle and performanceId are not the first member variables declared in the Performance class, my destructuring statement ends up being like this: 

val (_, _, _, _, _, danceTitle, performanceId) = performance

I'm not sure if this makes it less clear, I included it in the commit for now, I can take it out if need be.

2019-02-21 04:31 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +    private lateinit var adjudications: HashMap<*, *>
When I get the adjudications from the bundle, it comes as a serializable object that I need to cast to a HashMap. JVM (and Kotlin) erases the type arguments, so I can't check for these arguments and I have to cast to a generic HashMap.

2019-02-21 04:35 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/IDFetcher.kt
> +    fun registerCallback(db: FirebaseFirestore, callback: (Long) -> Unit) {
Franz said I should only acquire a FirebaseFirestore instance once since a lock is getting acquired when I invoke that function. I was having some issues with Firebase queries not working, and this change solved all of them for me.

2019-02-21 04:47 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/EventActivity.kt
> +                        //numJudges = if (numJudges == null) DEFAULT else numJudges as String
My bad, that was a temporary fix since we have some inconsistent data in Firebase that was causing crashes when I ran the app. I fixed it so the app doesn't crash if we get unexpected data types from the database.

2019-02-21 04:55 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +    companion object {
Definitely, that's a good idea.

2019-02-22 23:16 UTC, YangStephen reviewed
V2 :) Almost there.

2019-02-22 23:16 UTC, YangStephen commented on app/build.gradle
> +
extra line

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
>  </manifest>
new line terminator at the end of this file

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +import com.uwblueprint.dancefest.models.Adjudication.Companion.ARG_ARTISTIC_MARK
I'm hoping theres a way to just do something like import com.uwblueprint.....Adjudication.Companion.*?

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +    class PerformancePagerAdapter(
I'm curious if this should remain in here or if we should segment this out into it's own class. Not a big fan of classes in classes.

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                            if (academicLevel is String) academicLevel else DEFAULT,
I was trying to figure out if there was a way we could fix the styling on these lines for the assignment of a value to the constructor's field. One way I thought was we could create a helper function that accepts some value. If the value is a string, return the value else default.

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                                    adjudications,
this is an 8 space indent, let's bring it back to 4 please

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                            view_pager.addOnPageChangeListener(TabLayout.TabLayoutOnPageChangeListener(tab_layout))
This line is greater than the 100 char limit per line.

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                            tab_layout.addOnTabSelectedListener(object : TabLayout.OnTabSelectedListener {
This one as well.

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +            performances = getParcelableArrayList(PerformanceActivity.TAG_PERFORMANCES)
There's a type mismatch error here, we're casting a Java ArrayList to the kotlin.collections.arrayList

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformancesAdapter.kt
> +}
New Line

2019-02-22 23:16 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/models/Adjudication.kt
> +
I think we don't need this extra line

2019-02-23 18:00 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +import com.uwblueprint.dancefest.models.Adjudication.Companion.ARG_ARTISTIC_MARK
Unfortunately wildcard imports don't work on Kotlin objects, so this is our only option.

2019-02-23 19:18 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +            performances = getParcelableArrayList(PerformanceActivity.TAG_PERFORMANCES)
I think the Java ArrayList is mapped to the Kotlin ArrayList: http://kotlinlang.org/docs/reference/java-interop.html#mapped-types. I'm forced to use the Java one here because that's the type that getParcelableArrayList() returns.

2019-02-25 16:55 UTC, YangStephen approved these changes
Likely my last round of comments, mainly just questions on why we are doing certain things. We can cover them tonight, otherwise I think this should be fine to go in! Let's just hold off until we've had a change to discuss. :)

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/EventsAdapter.kt
> +class EventsAdapter(private val listener: EventItemListener, private val events: ArrayList<Event>) :
Does this constructor change break any existing initializations of EventsAdapter? Since the first parameter is no longer expected as events.

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +import com.uwblueprint.dancefest.models.Adjudication.Companion.ARG_ARTISTIC_MARK
This is a pretty intense import. Do you think it would be possible to do a single data class, that contains these ARTISTIC_MARK / etc. values, then in the companion object, we just initialize an instance of this data class? So all we'll do in the end is just import `Adjudication.Companion.DataClassObj` and we can deref the dataclass object later on for all the artistic marks? Ex. var(ARG_ARTISTIC_MARK, ARG_AUDIO_URL, etc.) = DataClassObj;

We can discuss it later on.

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceActivity.kt
> +                                    val artisticMark = adjDocData?.get(ARG_ARTISTIC_MARK)
Do these lines break the 100 char limit?

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +                newAdjudications
When you mentioned that you had to use a HashMap<*, *> here, what is the case when it is not a hashmap?

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformanceFragment.kt
> +            performances = getParcelableArrayList(PerformanceActivity.TAG_PERFORMANCES)
Hm interesting, I see the mapping but it looks like Android Studio doesn't recognize the underlying mapping.

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformancePagerAdapter.kt
> +}
New Line terminator on this file.

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/PerformancePagerAdapter.kt
> +                if (position == 0) incompletePerformances else completePerformances)
you might just be able to extra this into a variable and pass the variable instead.

```
val performances = if position == 0 incompletePerformances else completePerformances
putParcelableArrayList (..., performances)
```

2019-02-25 16:55 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +        inline fun <reified T> getVal(value: Any?, default: T) : T =
Why are we putting this function in a companion object rather than the FirestoreUtils class?

2019-02-26 00:06 UTC, merged