Add recording capabilities
uwblueprint/dancefest-android pull request #25
Opened 2019-03-09 05:32 UTC by Dendrimer

![image](https://user-images.githubusercontent.com/10265013/54066669-1323ec80-4202-11e9-924b-faac7f018a65.png)

![image](https://user-images.githubusercontent.com/10265013/54066677-1d45eb00-4202-11e9-9d6c-588bf6b0c66a.png)

![image](https://user-images.githubusercontent.com/10265013/54066679-246cf900-4202-11e9-8783-7e972a034bd7.png)

Implemented the recording button (Audio file field in form is still static, its a TODO).

The audio file saving workflow is as follows:
If the adjudication hasn't been saved, the audio file is saved to a local name which is different from the adjudication ID, as it's not available yet. If adjudication ID is available (i.e, it is in the "complete" tab in the performances screen), then the local audio file name will be the adjudication ID.

Recording an audio file before an adjudication is complete will not upload to Firebase Storage, as the associated Adjudication ID is not available yet. On first save, if an audio file has been recorded, it will send that audio file to Firebase. Subsequent recordings will then upload to the correct path in Firebase storage.

2019-03-09 19:08 UTC, danielpeng2 commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        ActivityCompat.requestPermissions(this, permissions, REQUEST_RECORDING_PERMISSION)
I think we want to run a check to make sure we only request these permissions if we don't already have them

2019-03-11 22:53 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        ActivityCompat.requestPermissions(this, permissions, REQUEST_RECORDING_PERMISSION)
I do that in `onRequestPermissions`, which I think? is the correct way to do it

2019-03-11 23:25 UTC, YangStephen requested changes
V1

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +    private var mRecorder: MediaRecorder? = null
can we alphabetize these declarations

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                    intent.getSerializableExtra(PerformanceFragment.TAG_PERFORMANCE) as Performance
can we minimize the diff change here.

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        // for the context of saving locally
period at the end of this sentence.

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        var audioName = performance.performanceId
we can destructure this data?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +
extra line is unnecessary

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            audioName = adjudication!!.adjudicationId
Rather than double `adjudication!!` here, we could just convert it to a non- nullable adjudication and use that reference.

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                        saveRecording(localFilePath, firebasePath!!)
The logic here confuses me a bit, why do we have 2 calls to saveRecording? Isn't the only time we're saving when we submit? Whats the saveRecording on line 104 do?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                adjudication!!.notes else EMPTY_STRING
Is there a way where maybe we dont need the double `!!` everytime here?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/res/drawable/ic_baseline_stop_24px.xml
> +    android:viewportWidth="24" android:width="42dp" xmlns:android="http://schemas.android.com/apk/res/android">
Can we segment these XML parameters per-line for readability?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/res/values/strings.xml
> +    <string name="stop_record_prompt">Are you sure you want to stop and save the recording?</string>
can we order these declarations in some matter (either by name or the  text itself?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        permissions: Array<out String>,
What does the `out` keyword do here?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            grantResults[0] == PackageManager.PERMISSION_GRANTED
how does this grandResults parameter work? Are there more parameters we should be concerned about?

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        if (!permissionToRecord) finish()
can we wrap the finish here in a `{ .. }`

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        // If external storage isn't available recording is impossible
`If external storage isn't available, recording is impossible.`

2019-03-11 23:25 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            finish()
What does finish do, should we return out of this?

2019-03-12 03:21 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                    intent.getSerializableExtra(PerformanceFragment.TAG_PERFORMANCE) as Performance
This is from me running the formatter

2019-03-12 03:26 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                        saveRecording(localFilePath, firebasePath!!)
This is to cover the case where a recording was made, but the adjudication wasn't submitted yet.

2019-03-12 03:26 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        permissions: Array<out String>,
This is the boilerplate for the implementation of the request permissions, it has something to do with generic return types in Kotlin

2019-03-13 00:57 UTC, Dendrimer commented on app/src/main/res/drawable/ic_baseline_stop_24px.xml
> +    android:viewportWidth="24" android:width="42dp" xmlns:android="http://schemas.android.com/apk/res/android">
This was autogenerated

2019-03-16 21:22 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            grantResults[0] == PackageManager.PERMISSION_GRANTED
This is just how the permissions are requested, its assigned to the first element in the array.

2019-03-16 21:23 UTC, Dendrimer commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            finish()
Finish just kills the recorder, no returning is needed

2019-03-17 01:06 UTC, YangStephen approved these changes
This should be fine, let's get this in ASAP so we can work on loading everything onto the tablets :).

Thanks Franz!

2019-03-18 22:37 UTC, merged