Saved Adjudication Form page
uwblueprint/dancefest-android pull request #26
Opened 2019-03-12 01:12 UTC by sophieq

- "Saved" Adjudication Form screen after you press "Save Critique" in Adjudication form

2019-03-12 15:12 UTC, YangStephen requested changes
@danielpeng2 @sophieq This is my first review, but after this it will be pretty close to merge.

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".EventActivity"
Let's keep this as how it was before, this change doesn't affect any functionality.

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
> +        <activity
Why did this have to be reordered?

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
> +</manifest>
new line at the end of this file

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +                "cumulativeMark" to cumulativeScore,
can we rename the variable to cumulativeMark as well for consistency

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +
this extra line is not needed

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        var navPath = "$eventTitle > ${performance.danceTitle}"
What happens if this overflows? I know this is because we have a lot of space on the top bar but I'm curious if we should just increase the limit to like 150 or something.

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            if (resultCode == Activity.RESULT_OK) {
What is this RESULT_OK? It that a boolean on if our submit succeeded / failed? What happens if we want to return to performances but this is not OK?

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/SavedCritiqueActivity.kt
> +
This extra line is unnecessary

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/SavedCritiqueActivity.kt
> +        super.onCreate(savedInstanceState)
I'd recommend we keep Super by itself and group setContentView / backButton.setOnClickListener.

```
super.....

setContentView
backButton
```

2019-03-12 15:12 UTC, YangStephen commented on app/src/main/res/layout/activity_saved_critique.xml
> +</android.support.constraint.ConstraintLayout>
new line at the end of this line please

2019-03-12 15:58 UTC, sophieq commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +        var navPath = "$eventTitle > ${performance.danceTitle}"
Instead of doing the truncating of navPath in the activity, I changed it in the XML, so that the text field can only display a max of 1 line. If the navPath is longer, it will truncate the string and add ellipses to the end

2019-03-12 16:02 UTC, sophieq commented on app/src/main/AndroidManifest.xml
> +        <activity
It didn't have to be, I just re-ordered it in alphabetical order.

2019-03-12 16:10 UTC, sophieq commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            if (resultCode == Activity.RESULT_OK) {
This is only used when we are at the "Saved Critique" activity and we want to return back to performance list (skip over adjudication form when we go "back". RESULT_OK is the result code that the "Saved Critique" page sends to the adjudication form, to let adjudication form know it its activity should also be closed . The "Saved Critique" activity gets set to RESULT_OK when the user pushes the "BACK TO PERFORMANCE LIST" button. In the "Saved Critique" page, the only option is to return to the performance page so every time the the result code has to be RESULT_OK.

2019-03-13 23:48 UTC, YangStephen approved these changes
I'm approving this for the demo tomorrow.

I'd like to investigate if the option I linked is viable and if there are side effects: ex. We lose the saved state in the performances activity / etc.

2019-03-13 23:48 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
> +        <activity
I'd prefer that we declare the Activities here in the order of the workflow Events > Performances > CritiqueForm > SavedForm etc.

2019-03-13 23:48 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/SavedCritiqueActivity.kt
> +            setResult(Activity.RESULT_OK)
I see what's going on here, this is sending a result on the activity that PerformanceActivity picks up and then goes back again.

Can we try the solution in here: https://stackoverflow.com/questions/20235697/go-back-to-2nd-previous-activity?
```
Intent intent = new Intent(Activity3.this,
                Activity1.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP
                | Intent.FLAG_ACTIVITY_SINGLE_TOP);
CLEAR_TOP is basically to pop off the top and go to the last occurance of the class in question from what I saw.
        startActivity(intent);
```

2019-03-13 23:48 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/CritiqueFormActivity.kt
> +            if (resultCode == Activity.RESULT_OK) {
Got it, The only thing I don't like about this implementation is that we have to rely on everything from the CritiqueForm and PerformanceActivity working in order to get back to performances. I know that Performances is somewhere in my history, I'd rather just directly go back to that Activity.

I made a comment below about a potential solution, let me know if you think that's viable.

2019-03-15 00:54 UTC, YangStephen approved these changes
Nice Sophie! Sorry for the accidental push, this branch should now be clean to only include your work and Dan's :)

2019-03-15 00:54 UTC, YangStephen commented on app/src/main/AndroidManifest.xml
> +
Remove this one line

2019-03-15 17:11 UTC, YangStephen commented
@sophieq @danielpeng2 This is ok to merge into master whenever you are ready.

2019-03-16 19:16 UTC, merged