Create Firestore Wrapper Class
uwblueprint/dancefest-android pull request #9
Opened 2019-01-11 01:52 UTC by mark-azer

2019-01-11 02:42 UTC, YangStephen requested changes
Nice work Mark! Just a few comments regarding styling / functions.

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +                .setTimestampsInSnapshotsEnabled(true)
Can we standardize the styling here, the indentation looks off.

Let's follow the Kotlin style guide : https://kotlinlang.org/docs/reference/coding-conventions.html. Applicable Section is called ```Chained Call wrapping```

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +        db.collection(collectionName)
Standardize styling

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +    fun addData(collectionName: String, data: HashMap<String, Any?>) : Unit {
I haven't checked this exact line length but if it is greater than 100 characters, let's line wrap it.

Ref:
100 char style guide limit: https://developer.android.com/kotlin/style-guide
Function header formatting: https://kotlinlang.org/docs/reference/coding-conventions.html#function-formatting

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +                    Log.w(TAG, "Error adding document", e)
If this is a failure, I'd almost rather Log.e rather than Log.w. If there is a failure here, i would personally consider it an error. However, we should verify if adding a document while offline goes to the success listener or the failure listener.

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +package com.uwblueprint.dancefest.firebase
Do we have a function in this class to get data?

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +                    Log.w(TAG, "Error writing document", e)
Log.e here potentially.

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +    fun updateData(collectionName: String, docName: String, data: HashMap<String, Any?>) : Unit {
Same comment as above with the function styling, I'm almost certain this one passes 100 characters.

2019-01-11 02:42 UTC, YangStephen commented on app/src/main/java/com/uwblueprint/dancefest/firebase/FirestoreUtils.kt
> +        FirebaseFirestoreSettings.Builder()
Do we not need to provide in our firebase configs into this class? Like the URLs, API keys, etc? The idea was to make the constructor an initializer for our Firebase instance.

2019-01-12 21:42 UTC, Dendrimer commented
LGTM 🚢

2019-01-12 21:45 UTC, Dendrimer approved these changes
LGTM :shipit:

2019-01-12 21:45 UTC, merged